<?php
	/*
		Any object that allows comments must set these values in the controller.
		They are an integral part of Gryphon's spam and robot traps.
		
		All that really matters is that they are present in the method outlined
		below.
		
		Generally you should leave this form as unchanged as possible. If you
		must alter it, please remember to keep the name and id attributes 
		the same and do not alter or remove the hidden elements.
	*/
	
	// The key is a unique value generated by the server and stored in the
	// session. This keeps people from using auto posting scripts
	$key = Foundry::registry( 'sys:comment.key', false );
	
	// The Turing quesion, if enabled, keeps people from using auto posting
	// scripts
	$question = Foundry::registry( 'sys:comment.question', false );

	// This describes the type of content we're commenting on (article, media, 
	// etc).
	$type = Foundry::registry( 'sys:comment.type', false );

	// Plugins set this flag
	$plugin = Foundry::registry( 'sys:comment.plug', false );

	// This tells the comment system the ID of the object being commented on
	$id = Foundry::registry( 'sys:comment.objectID', false );
?>
<h2>Join the discussion</h2>
	
<form id="commentform" action="<?php echo Foundry::link( 'comment/' ) ?>" method="post">
	<?php // These items are required ?>
	<input type="hidden" name="commentKey" value="<?php echo $key ?>" />
	<input type="hidden" name="<?php echo $key ?>" value="<?php echo $question->uid ?>" />
	<input type="hidden" name="id" value="<?php echo $id ?>" />
	<input type="hidden" name="type" value="<?php echo $type ?>" />
	<input type="hidden" name="plug" value="<?php echo $plugin ?>" />

	<fieldset id="comment-userinfo">
		<input type="text" name="name" id="comment_name" value="Your Name" class="clearMeFocus" />
		<input type="text" name="email" id="comment_email" value="Your Email (won't be published)" />
	</fieldset>
	<fieldset>
		<textarea name="comment" id="comment_body">Your Comment</textarea>
		
		<?php
		$question = GFNTuring::random();
		$sess = Foundry_User_Session::load();
		$key = $sess->get( 'turingKey' );
		?>
		<input type="hidden" name="<?php echo $key ?>" value="<?php echo $question->uid ?>" />
		<input type="text" name="answer" id="comment_turing" size="40" value="<?php echo $question->question ?>" class="clearme rounded" />		
	</fieldset>

	<input type="submit" id="comment_submit" value="Add Comment" />			
</form>